### ISSUE TITLE
Run and Build missing dependency `react-is`

### ISSUE THREAD

**Issue by PathToLife** [WalletConnect/walletconnect-example-dapp#71] opened 2021-09-16 19:34 UTC
# description
Clone master for the first time.

Run a successful `npm install`

# error

`npm run build`

Gives the following error

```
> react-scripts-ts build

Creating an optimized production build...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
(node:3084) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Failed to compile.

Module not found: Error: Can't resolve 'react-is' in 'C:\Development\***\walletconnect-example-dapp\node_modules\styled-components\dist'
```

`npm run start`

Gives a similar error, module not found `react-is`

## my fix

`npm i react-is`

## env
- node v14.16.0
- npm 7.19.0

**Comment by bkrem** [comment] 2022-01-31 16:14
Closing since this does not seem to be reproducible anymore. Cloning a fresh copy + `npm install` + `npm run build` seem to work as expected.

Please comment here if it's still reproducible and I will reopen.

**Closed by bkrem** 2022-01-31 16:14 UTC
